# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7aab54d4d5a226ae92a74c28329040e45cb07761b9110cb63af8b0d93a00d9f2678661df77bd2a2111ae6b1b2adf9e8d2bd512b440e91b6a6cca3741a50bafaa

test:
  secret_key_base: 814aae595ddcca103bd2d64c7f1a5f759858147ec6b9120f8290b0804f079491102a2e36641be5babddb260404b72de16be3eeaa4daa345f8874ab50ecc1cff0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
